---
title: "Directory_homework"
author: "Makayla Hayes"
date: "2/4/2021"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(xml2)
library(rvest)
library(dplyr)
```

```{r}
#First load in HTML verson on website
simple<-read_html("https://guide.wisc.edu/faculty/")
sample

#Next I changes all the <br> to <p>\n in order to be able to space
#the different categories for the individual person
xml_find_all(simple,".//br")%>%
  xml_add_sibling("p","\n")
xml_find_all(simple,".//br")%>%
  xml_remove()  

#Then I pull out each line of text which is equivent to each persons information
text_out<-simple%>%
  html_nodes(".uw-people")%>%
  html_nodes("li")%>%
  html_nodes("p")
head(text_out)

#Then I take out all the extra lines
bad<-list()
good<-list()
k=1
j=1
for (i in 1:length(text_out)) {
  if(html_text(text_out[i])=="\n"){
        bad[k]<-html_text(text_out[i])
        k=k+1
  }
else{
  good[j]<-html_text(text_out[i])
  j=j+1
}
}

#Then I extract each person name,job,field,PHD information and
#Put them into separate lists
good<-unlist(good)
names<-list()
job<-list()
field<-list()
PHD<-list()
for(i in 1:length(good)){
 temp<-unlist(strsplit(good[i],"\n"))
 if(length(temp)==4){
   names[i]<-temp[1]
   job[i]<-temp[2]
   field[i]<-temp[3]
   PHD[i]<-temp[4]
 }
 else if (length(temp)==3){
   names[i]<-temp[1]
   job[i]<-temp[2]
   field[i]<-temp[3]
   PHD[i]<-""
 }
}
#Lastly I convert the lists to vectors and
#store them all into a dataframe for convenience
Name<-c(1:3988)
Position<-c(1:3988)
Department<-c(1:3988)
Degree<-c(1:3988)
for(i in 1:3988){
  Name[i]<-unlist(names[i])
  Position[i]<-unlist(job[i])
  Department[i]<-unlist(field[i])
  Degree[i]<-unlist(PHD[i])
}
directory<-data.frame(Name,Position,Department,Degree)
head(directory)
```

https://github.com/makaylahayes/Directory_homework_tmp
